<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.302">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>parcial</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="parcial_files/libs/clipboard/clipboard.min.js"></script>
<script src="parcial_files/libs/quarto-html/quarto.js"></script>
<script src="parcial_files/libs/quarto-html/popper.min.js"></script>
<script src="parcial_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="parcial_files/libs/quarto-html/anchor.min.js"></script>
<link href="parcial_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="parcial_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="parcial_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="parcial_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="parcial_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script src="https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.6/require.min.js" integrity="sha512-c3Nl8+7g4LMSTdrm621y7kf9v3SDPnhxLNhcjFJbKECVnmZHTdo+IRO05sNLTH/D3vA6u1X32ehoLC7WFVdheg==" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js" integrity="sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg==" crossorigin="anonymous"></script>
<script type="application/javascript">define('jquery', [],function() {return window.jQuery;})</script>


</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">



<p>Parcial estadística avanzada</p>
<p>Eduardo Avendaño Caicedo</p>
<div class="cell" data-execution_count="1">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co">#se importan las librerias que se utilizaran para el desarrollo del parcial, se usará python como lenguaje de programación.</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> scipy <span class="im">as</span> sc</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> statsmodels.api <span class="im">as</span> sm</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.linear_model <span class="im">import</span> LogisticRegression</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Para el primer punto se filtrará la base de datos:</p>
<div class="cell" data-execution_count="2">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>df <span class="op">=</span> pd.read_excel(<span class="vs">r'C:\Users\Eduardo\Desktop\parcialEstadistica\datos.xlsx'</span>)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>filtro <span class="op">=</span> (df[<span class="st">'Barrio'</span>] <span class="op">==</span> <span class="st">'el ingenio'</span>) <span class="co">#aplicamos el filtro para el barrio "el ingenio"</span></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>df_filtrado1 <span class="op">=</span> df.loc[filtro, [<span class="st">'precio_millon'</span>, <span class="st">'Area_contruida'</span>]] <span class="co">#se seleccionan las variables de precio por millon y area construida </span></span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a>df_filtrado1</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="2">
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">precio_millon</th>
<th data-quarto-table-cell-role="th">Area_contruida</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">36</td>
<td>1450.0</td>
<td>1200.0</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">122</td>
<td>290.0</td>
<td>100.0</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">220</td>
<td>360.0</td>
<td>99.0</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">581</td>
<td>550.0</td>
<td>197.0</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2396</td>
<td>410.0</td>
<td>136.0</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">...</td>
<td>...</td>
<td>...</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">6516</td>
<td>176.0</td>
<td>83.0</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">6894</td>
<td>980.0</td>
<td>750.0</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">7436</td>
<td>395.0</td>
<td>300.0</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">7462</td>
<td>230.0</td>
<td>85.0</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">7463</td>
<td>305.0</td>
<td>93.0</td>
</tr>
</tbody>
</table>

<p>202 rows × 2 columns</p>
</div>
</div>
</div>
<p>Disponemos de dos variables: precio por millon y Area construida. La variable independiente para nuestro modelo será el área construida y el precio dependerá de esta:</p>
<div class="cell" data-execution_count="3">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co">#escribo ambas variables como vectores de numpy:</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>X<span class="op">=</span>df_filtrado1[<span class="st">'Area_contruida'</span>].values</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>Y<span class="op">=</span>df_filtrado1[<span class="st">'precio_millon'</span>].values</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Primero se verificará el supuesto de normalidad en el conjunto de datos:</p>
<div class="cell" data-execution_count="4">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>X<span class="op">=</span>df_filtrado1[<span class="st">'Area_contruida'</span>].values</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>Y<span class="op">=</span>df_filtrado1[<span class="st">'precio_millon'</span>].values</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a><span class="co">#procedemos a hacer el test de normalidad de Shapiro-Wilk utilizando la libería scipy:</span></span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>stat1, pvalue1 <span class="op">=</span> sc.stats.shapiro(X)</span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a>stat2, pvalue2 <span class="op">=</span> sc.stats.shapiro(Y)</span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a>                                          </span>
<span id="cb4-9"><a href="#cb4-9" aria-hidden="true" tabindex="-1"></a><span class="co">#realizamos las pruebas de hipotesis respecto a los valores 'p' obtenidos anteriormente:</span></span>
<span id="cb4-10"><a href="#cb4-10" aria-hidden="true" tabindex="-1"></a><span class="co">#                                          </span></span>
<span id="cb4-11"><a href="#cb4-11" aria-hidden="true" tabindex="-1"></a>alpha <span class="op">=</span> <span class="fl">0.05</span></span>
<span id="cb4-12"><a href="#cb4-12" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> pvalue1 <span class="op">&gt;</span> alpha:</span>
<span id="cb4-13"><a href="#cb4-13" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="st">'No se rechaza la hipótesis nula: los datos X parecen ser normales, pvalor='</span> ,pvalue1)</span>
<span id="cb4-14"><a href="#cb4-14" aria-hidden="true" tabindex="-1"></a><span class="cf">else</span>:</span>
<span id="cb4-15"><a href="#cb4-15" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="st">'Se rechaza la hipótesis nula: los datos X no parecen ser normales, pvalor= '</span>,pvalue1)</span>
<span id="cb4-16"><a href="#cb4-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-17"><a href="#cb4-17" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> pvalue2 <span class="op">&gt;</span> alpha:</span>
<span id="cb4-18"><a href="#cb4-18" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="st">'No se rechaza la hipótesis nula: los datos Y parecen ser normales, pvalor='</span>, pvalue2)</span>
<span id="cb4-19"><a href="#cb4-19" aria-hidden="true" tabindex="-1"></a><span class="cf">else</span>:</span>
<span id="cb4-20"><a href="#cb4-20" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="st">'Se rechaza la hipótesis nula: los datos Y no parecen ser normales, pvalor='</span>,pvalue2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Se rechaza la hipótesis nula: los datos X no parecen ser normales, pvalor=  1.940874048622732e-18
Se rechaza la hipótesis nula: los datos Y no parecen ser normales, pvalor= 3.3113507934474408e-15</code></pre>
</div>
</div>
<p>Como vemos, nuestras variables de precio por millon y area construida no se distribuyen normalmente ya que tienen p-valores significativamente mas pequeños que nuestro nivel de significancia, se rechazan ambas hipotesis nula y concluimos que los datos no parecen ser normales.</p>
<p>Procedemos ahora a hacer nuestro modelo de regresión lineal:</p>
<div class="cell" data-execution_count="5">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>a,b<span class="op">=</span>np.polyfit(X,Y,<span class="dv">1</span>) <span class="co">#Regresión lineal simple</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> aprox(x):<span class="cf">return</span> a<span class="op">*</span>x<span class="op">+</span>b <span class="co">#construimos nuestra función de aproximación </span></span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>t<span class="op">=</span>np.linspace(<span class="bu">min</span>(X),<span class="bu">max</span>(X))<span class="co"># construimos un vector auxiliar que nos ayude a visualizar nuestra aproximación</span></span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a>plt.scatter(X,Y,label<span class="op">=</span><span class="st">'Dispersión'</span>)</span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-9"><a href="#cb6-9" aria-hidden="true" tabindex="-1"></a>plt.plot(t,aprox(t),<span class="st">'r'</span>,label<span class="op">=</span><span class="st">'Regresión'</span>)</span>
<span id="cb6-10"><a href="#cb6-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-11"><a href="#cb6-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-12"><a href="#cb6-12" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">'Area construida'</span>)</span>
<span id="cb6-13"><a href="#cb6-13" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">'Precio por millon'</span>)</span>
<span id="cb6-14"><a href="#cb6-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-15"><a href="#cb6-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-16"><a href="#cb6-16" aria-hidden="true" tabindex="-1"></a>plt.legend()</span>
<span id="cb6-17"><a href="#cb6-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-18"><a href="#cb6-18" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(a,b)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>1.2115947787538606 195.71496397620126</code></pre>
</div>
<div class="cell-output cell-output-display">
<p><img src="parcial_files/figure-html/cell-6-output-2.png" width="601" height="429"></p>
</div>
</div>
<p>Procedemos ahora a hacer un gráfico de dispersión de los residuos de nuestro modelo:</p>
<div class="cell" data-execution_count="6">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>residuos <span class="op">=</span> Y <span class="op">-</span> a<span class="op">*</span>X <span class="op">-</span> b</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>plt.scatter(a<span class="op">*</span>X<span class="op">+</span>b,residuos)</span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>plt.axhline(y<span class="op">=</span><span class="dv">0</span>, color<span class="op">=</span><span class="st">'r'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="6">
<pre><code>&lt;matplotlib.lines.Line2D at 0x23e14865610&gt;</code></pre>
</div>
<div class="cell-output cell-output-display">
<p><img src="parcial_files/figure-html/cell-7-output-2.png" width="586" height="411"></p>
</div>
</div>
<p>El diagrama de residuos sugiere que no hay homocedasticidad.</p>
<p>Nuestros datos no se distribuyen normalmente y no se cumple el supuesto de homocedasticidad, por otra parte, en nuestro diagrama de dispersión podemos ver inicialmente que existe cierta linealidad en las variables, sin embargo, no recomendaría utilizar la regresión lineal simple en este caso debido al incumplimiento de los dos supuestos mencionados anteriormente.</p>
<p>Para la siguiente parte de nuestro ejercicio, debemos incluir la variable ‘tipo’ y realizar una regresión categórica.</p>
<p>Iniciamos creando un nuevo “dataframe” filtrado el cual tenga esta variable:</p>
<div class="cell" data-execution_count="7">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>df_filtrado2 <span class="op">=</span> df.loc[filtro, [<span class="st">'precio_millon'</span>, <span class="st">'Area_contruida'</span>,<span class="st">'Tipo'</span>]]</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>df_filtrado2</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="7">
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">precio_millon</th>
<th data-quarto-table-cell-role="th">Area_contruida</th>
<th data-quarto-table-cell-role="th">Tipo</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">36</td>
<td>1450.0</td>
<td>1200.0</td>
<td>Casa</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">122</td>
<td>290.0</td>
<td>100.0</td>
<td>Apartamento</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">220</td>
<td>360.0</td>
<td>99.0</td>
<td>Apartamento</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">581</td>
<td>550.0</td>
<td>197.0</td>
<td>Apartamento</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2396</td>
<td>410.0</td>
<td>136.0</td>
<td>Apartamento</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">...</td>
<td>...</td>
<td>...</td>
<td>...</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">6516</td>
<td>176.0</td>
<td>83.0</td>
<td>Apartamento</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">6894</td>
<td>980.0</td>
<td>750.0</td>
<td>Casa</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">7436</td>
<td>395.0</td>
<td>300.0</td>
<td>Casa</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">7462</td>
<td>230.0</td>
<td>85.0</td>
<td>Apartamento</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">7463</td>
<td>305.0</td>
<td>93.0</td>
<td>Apartamento</td>
</tr>
</tbody>
</table>

<p>202 rows × 3 columns</p>
</div>
</div>
</div>
<p>Para realizar el análisis debemos volver la variable ‘tipo’ es una variable dummie:</p>
<div class="cell" data-execution_count="8">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>dummies <span class="op">=</span> pd.get_dummies(df_filtrado2[<span class="st">"Tipo"</span>])</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>df_filtrado2 <span class="op">=</span> pd.concat([df_filtrado2, dummies], axis<span class="op">=</span><span class="dv">1</span>)</span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>df_filtrado2</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="8">
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">precio_millon</th>
<th data-quarto-table-cell-role="th">Area_contruida</th>
<th data-quarto-table-cell-role="th">Tipo</th>
<th data-quarto-table-cell-role="th">Apartamento</th>
<th data-quarto-table-cell-role="th">Casa</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">36</td>
<td>1450.0</td>
<td>1200.0</td>
<td>Casa</td>
<td>0</td>
<td>1</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">122</td>
<td>290.0</td>
<td>100.0</td>
<td>Apartamento</td>
<td>1</td>
<td>0</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">220</td>
<td>360.0</td>
<td>99.0</td>
<td>Apartamento</td>
<td>1</td>
<td>0</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">581</td>
<td>550.0</td>
<td>197.0</td>
<td>Apartamento</td>
<td>1</td>
<td>0</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2396</td>
<td>410.0</td>
<td>136.0</td>
<td>Apartamento</td>
<td>1</td>
<td>0</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">6516</td>
<td>176.0</td>
<td>83.0</td>
<td>Apartamento</td>
<td>1</td>
<td>0</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">6894</td>
<td>980.0</td>
<td>750.0</td>
<td>Casa</td>
<td>0</td>
<td>1</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">7436</td>
<td>395.0</td>
<td>300.0</td>
<td>Casa</td>
<td>0</td>
<td>1</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">7462</td>
<td>230.0</td>
<td>85.0</td>
<td>Apartamento</td>
<td>1</td>
<td>0</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">7463</td>
<td>305.0</td>
<td>93.0</td>
<td>Apartamento</td>
<td>1</td>
<td>0</td>
</tr>
</tbody>
</table>

<p>202 rows × 5 columns</p>
</div>
</div>
</div>
<p>Teniendo nuestras variables dummies, crearemos vectores auxiliares “Aaux” y “Yaux” para agregar nuestras variables dependientes (Area y la variable categorica del tipo de vivienda) y nuestra variable independiente (precio):</p>
<div class="cell" data-execution_count="9">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>Xaux<span class="op">=</span> df_filtrado2[[<span class="st">"Area_contruida"</span>, <span class="st">"Casa"</span>]]</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>Yaux<span class="op">=</span> df_filtrado2[<span class="st">"precio_millon"</span>]</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>Xaux<span class="op">=</span> sm.add_constant(Xaux)</span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a>modeloCategorico <span class="op">=</span> sm.OLS(Yaux, Xaux).fit() <span class="co">#OLS es la función de statsmodels equivalente a RC del lenguage de programación "R"</span></span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-8"><a href="#cb12-8" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(modeloCategorico.summary())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                            OLS Regression Results                            
==============================================================================
Dep. Variable:          precio_millon   R-squared:                       0.802
Model:                            OLS   Adj. R-squared:                  0.800
Method:                 Least Squares   F-statistic:                     403.1
Date:                Thu, 20 Apr 2023   Prob (F-statistic):           1.02e-70
Time:                        12:33:53   Log-Likelihood:                -1212.7
No. Observations:                 202   AIC:                             2431.
Df Residuals:                     199   BIC:                             2441.
Df Model:                           2                                         
Covariance Type:            nonrobust                                         
==================================================================================
                     coef    std err          t      P&gt;|t|      [0.025      0.975]
----------------------------------------------------------------------------------
const            196.1196     10.916     17.967      0.000     174.594     217.645
Area_contruida     1.0220      0.056     18.196      0.000       0.911       1.133
Casa              99.2499     18.631      5.327      0.000      62.510     135.990
==============================================================================
Omnibus:                       45.694   Durbin-Watson:                   1.965
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              169.888
Skew:                           0.835   Prob(JB):                     1.29e-37
Kurtosis:                       7.171   Cond. No.                         674.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.</code></pre>
</div>
</div>
<p>Todos los coeficientes tienen asociado un valor p, que indica si el coeficiente es significativamente diferente de cero o no. En este caso, todos los coeficientes tienen valores de p muy bajos (p &lt; 0.05), lo que indica que son significativamente diferentes de cero y, por lo tanto, son importantes en el modelo.</p>
<p>El coeficiente de la constante (intercepto) es 196.1196, lo que significa que para una vivienda con un área construida de cero y que sea un apartamento, se espera que tenga un precio de 196.1196 millones de pesos. Sin embargo, este valor no tiene un significado práctico ya que una vivienda con un área construida de cero no existe en la realidad.</p>
<p>El coeficiente de “Area_contruida” es de 1.0220, lo que significa que se espera que por cada aumento de una unidad en el área construida, el precio de la vivienda aumente en 1.0220 millones de pesos, manteniendo constante el tipo de vivienda.</p>
<p>Ahora se realizará el analisis de varianza comparando el modelo de regresión lineal simple con el último en el que añadimos la variable “Tipo”:</p>
<div class="cell" data-execution_count="10">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>modeloLineal<span class="op">=</span> sm.OLS(Y, sm.add_constant(X)).fit() <span class="co">#Para uso practico, usaremos el modelo lineal de la libreria "Statsmodels""ETICA CASO 2-final.docx"</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> statsmodels.stats.anova <span class="im">import</span> anova_lm <span class="co">#Usamos la función de anova de stats models</span></span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Análisis de varianza</span></span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a>anova_results <span class="op">=</span> anova_lm(modeloLineal, modeloCategorico)</span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-8"><a href="#cb14-8" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(anova_results)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   df_resid           ssr  df_diff        ss_diff         F        Pr(&gt;F)
0     200.0  2.214303e+06      0.0            NaN       NaN           NaN
1     199.0  1.937949e+06      1.0  276353.632567  28.37761  2.687289e-07</code></pre>
</div>
</div>
<p>El modelo categórico tiene un valor F de 28.37761 y un valor p de 2.687289e-07, mientras que el modelo lineal no tiene un valor F ni un valor p significativos. Por lo tanto, se puede concluir que el modelo categórico es mejor que el modelo lineal.</p>
<p>La variable “Tipo” tiene una gran importancia en nuestro modelo, esto es algo que concluímos del modelo de regresión categórico.</p>
<p>Segundo punto.</p>
<p>Para este caso se trabajará con una base de datos que contiene la edad y masa de 60 individuos.</p>
<p>Para nuestro modelo, la masa dependerá de la edad:</p>
<div class="cell" data-execution_count="11">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Se carga la base de datosME</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>df2 <span class="op">=</span> pd.read_excel(<span class="vs">r'C:\Users\Eduardo\Desktop\parcialEstadistica\datosME.xlsx'</span>) <span class="co">#leer base de datos </span></span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a>X1<span class="op">=</span>df2[<span class="st">'Edad'</span>]</span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a>Y1<span class="op">=</span>df2[<span class="st">'Masa'</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Definimos Xi = X - mean(X), lo hacemos para centrar la variable.</p>
<p>Procedeos a hacer la regresión utilizando un polinomio cuadrático:</p>
<div class="cell" data-execution_count="12">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>Xi<span class="op">=</span> X1<span class="op">-</span>np.mean(X1) <span class="co">#centralizar la variable</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>a1,b1,c1<span class="op">=</span>np.polyfit(Xi, Y1, <span class="dv">2</span>) <span class="co">#función de regresión cuadrática de numpy</span></span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> aprox2(x): <span class="cf">return</span> a1<span class="op">*</span>x<span class="op">**</span><span class="dv">2</span> <span class="op">+</span> b1<span class="op">*</span>x <span class="op">+</span> c1  <span class="co">#creación del modelo utilizando los parámetros encontrados con la función polyfit</span></span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-7"><a href="#cb17-7" aria-hidden="true" tabindex="-1"></a>t2<span class="op">=</span>np.linspace(<span class="bu">min</span>(Xi),<span class="bu">max</span>(Xi)) <span class="co">#vector auxiliar </span></span>
<span id="cb17-8"><a href="#cb17-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-9"><a href="#cb17-9" aria-hidden="true" tabindex="-1"></a><span class="co">#gráfica de dispersión</span></span>
<span id="cb17-10"><a href="#cb17-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-11"><a href="#cb17-11" aria-hidden="true" tabindex="-1"></a>plt.scatter(Xi,Y1)</span>
<span id="cb17-12"><a href="#cb17-12" aria-hidden="true" tabindex="-1"></a>plt.plot(t2,aprox2(t2),<span class="st">'r'</span>)</span>
<span id="cb17-13"><a href="#cb17-13" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">'Edad'</span>)</span>
<span id="cb17-14"><a href="#cb17-14" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">'Masa'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="12">
<pre><code>Text(0, 0.5, 'Masa')</code></pre>
</div>
<div class="cell-output cell-output-display">
<p><img src="parcial_files/figure-html/cell-13-output-2.png" width="593" height="429"></p>
</div>
</div>
<p>En el diagrama de dispersión podemos ver cierta linealidad entre las variables.</p>
<div class="cell" data-execution_count="13">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>Xaux <span class="op">=</span> sm.add_constant(np.column_stack((Xi, Xi<span class="op">**</span><span class="dv">2</span>)))</span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Ajustar modelo de regresión cuadrática</span></span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a>modeloCuadratico <span class="op">=</span> sm.OLS(Y1, Xaux).fit()</span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(modeloCuadratico.summary())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                            OLS Regression Results                            
==============================================================================
Dep. Variable:                   Masa   R-squared:                       0.778
Model:                            OLS   Adj. R-squared:                  0.770
Method:                 Least Squares   F-statistic:                     99.80
Date:                Thu, 20 Apr 2023   Prob (F-statistic):           2.39e-19
Time:                        12:33:54   Log-Likelihood:                -208.96
No. Observations:                  60   AIC:                             423.9
Df Residuals:                      57   BIC:                             430.2
Df Model:                           2                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P&gt;|t|      [0.025      0.975]
------------------------------------------------------------------------------
const         82.5269      1.241     66.477      0.000      80.041      85.013
x1            -1.1874      0.085    -13.900      0.000      -1.358      -1.016
x2             0.0084      0.004      2.065      0.043       0.000       0.016
==============================================================================
Omnibus:                        1.436   Durbin-Watson:                   2.452
Prob(Omnibus):                  0.488   Jarque-Bera (JB):                1.454
Skew:                           0.312   Prob(JB):                        0.483
Kurtosis:                       2.561   Cond. No.                         379.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.</code></pre>
</div>
</div>
<p>En este caso, el coeficiente estimado para la variable x1 es -1.1874, lo que indica que por cada unidad que aumenta x1, la variable dependiente “Masa” disminuye en promedio 1.1874 unidades, manteniendo el resto de las variables constantes. Por otro lado, el coeficiente estimado para la variable x2 es 0.0084, lo que indica que por cada unidad que aumenta x2, la variable dependiente “Masa” aumenta en promedio 0.0084 unidades, manteniendo el resto de las variables constantes. Ambos coeficientes son significativamente diferentes de cero, con valores p menores que 0.05.</p>
<p>En la tabla de resultados de la regresión cuadrática proporcionada, podemos ver que el coeficiente para el término cuadrático (x2) tiene un valor de 0.0084, con un error estándar de 0.004. Esto indica que existe una relación significativa entre la variable independiente cuadrática y la variable dependiente, y sugiere que el término cuadrático no debería ser eliminado del modelo.</p>
<p>Para el último índice, haremos un análisis de correlación entre la variables dependientes (centralizada y no centralizada) y su cuadrado.</p>
<p>Haremos uso de la función corrcoef de numpy para calcular la matriz de correlación:</p>
<div class="cell" data-execution_count="14">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(np.corrcoef(X,X<span class="op">**</span><span class="dv">2</span>))</span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>plt.scatter(X1,X1<span class="op">**</span><span class="dv">2</span>)</span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">'Masa'</span>)</span>
<span id="cb21-6"><a href="#cb21-6" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">'Masa^2'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[[1.         0.92107978]
 [0.92107978 1.        ]]</code></pre>
</div>
<div class="cell-output cell-output-display" data-execution_count="14">
<pre><code>Text(0, 0.5, 'Masa^2')</code></pre>
</div>
<div class="cell-output cell-output-display">
<p><img src="parcial_files/figure-html/cell-15-output-3.png" width="610" height="429"></p>
</div>
</div>
<p>En el caso de la matriz que muestras, la correlación de 0.921 entre las dos variables indica una fuerte relación lineal entre ellas, lo que podría dar lugar a problemas de multicolinealidad en un modelo de regresión que incluya ambas variables.</p>
<div class="cell" data-execution_count="15">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(np.corrcoef(Xi,Xi<span class="op">**</span><span class="dv">2</span>))</span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a>plt.scatter(Xi,Xi<span class="op">**</span><span class="dv">2</span>)</span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">'Masa centralizada'</span>)</span>
<span id="cb24-5"><a href="#cb24-5" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">'Masa^2 centralizada'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[[1.         0.32080009]
 [0.32080009 1.        ]]</code></pre>
</div>
<div class="cell-output cell-output-display" data-execution_count="15">
<pre><code>Text(0, 0.5, 'Masa^2 centralizada')</code></pre>
</div>
<div class="cell-output cell-output-display">
<p><img src="parcial_files/figure-html/cell-16-output-3.png" width="602" height="429"></p>
</div>
</div>
<p>la correlación entre las dos variables es moderada (0.32), lo que indica que existe cierta relación lineal entre ellas, pero no es tan fuerte como en los casos anteriores, por lo tanto, si es justificable la centralización de la variable dependiente.</p>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>